--- curl -v http://spring-boot-rest-client-svc:8080/ping
--- curl -v http://spring-boot-rest-client-svc.tutorial:8080/ping
--- curl -v http://spring-boot-rest-client-svc.tutorial.svc.cluster.local:8080/ping

--- curl -v http://spring-boot-rest-server-svc:8080/ping
--- curl -v http://spring-boot-rest-server-svc.tutorial2:8080/ping
--- curl -v http://spring-boot-rest-server-svc.tutorial2.svc.cluster.local:8080/ping

--- curl -v http://spring-boot-rest-client-tutorial.apps-crc.testing/ping

--- curl -v -HHost:spring-boot-rest-client-tutorial.apps-crc.testing http://ingress-api-gateway-svc.tutorial/ping
--- curl -v -HHost:spring-boot-rest-client-tutorial.apps-crc.testing http://egress-api-gateway-svc.tutorial2/ping
--- curl -v -HHost:spring-boot-rest-client-tutorial.apps-crc.testing http://spring-boot-rest-client-svc.tutorial.svc.cluster.local:8080/ping

--- curl -v http://mac.local.host/ping
--- curl -v http://mac.local.host:8080/ping

--- Запрещаем все взаимодействия внутри SM

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: istio-system
spec:
  {}

--- Разрешаем любое взаимодействие внутри Namespace

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-inner-communications
  namespace: tutorial
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["tutorial", "istio-system"]

--- Разрешаем любое взаимодействие внутри Namespace

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-inner-communications
  namespace: tutorial2
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["tutorial2", "istio-system"]

---

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-access-to-ingress
  namespace: istio-system
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: ingress-api-gateway
  rules:
    ### TODO-выяснить применимо ли к TCP
    - {}

---


apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-access-to-egress
  namespace: istio-system
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: egress-api-gateway
  rules:
    ### TODO-выяснить применимо ли к TCP
    - {}


---


apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-access-from-egress
  namespace: tutorial2
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: egress-api-gateway
  rules:
    - from:
        - source:
            namespaces: ["tutorial2"]
#            principals: ["cluster.local/ns/tutorial2/sa/*"]


--- Разрешаем обращение к сервисам SM снаружи, через Router
--- curl -v http://spring-boot-rest-client-tutorial.apps-crc.testing/ping

#oc apply -f - <<EOF
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: allow-access-to-ingress
#  namespace: istio-system
#spec:
#  action: ALLOW
#  selector:
#    matchLabels:
#      app: ingress-api-gateway
#  rules:
#    ### TODO-выяснить применимо ли к TCP
#    - {}
#EOF
---
#oc apply -f - <<EOF
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: allow-full-access-to-ingress
#  namespace: istio-system
#spec:
#  action: ALLOW
#  selector:
#    matchLabels:
#      app: ingress-api-gateway
#  rules:
#    - to:
#        - operation:
#            {}
#EOF

---

#oc apply -f - <<EOF
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: allow-full-access-from-egress
#  namespace: tutorial2
#spec:
#  action: ALLOW
#  selector:
#    matchLabels:
#      app: egress-api-gateway
#  rules:
#    - from:
#        - source:
#            principals: ["cluster.local/ns/tutorial2/sa/*"]
#    - to:
#        - operation:
#            {}
#EOF
---
#oc apply -f - <<EOF
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: allow-access-to-egress
#  namespace: tutorial2
#spec:
#  action: ALLOW
#  selector:
#    matchLabels:
#      app: egress-api-gateway
#  rules:
#    - to:
#        - operation:
#            ports: ["443", "80", "8080"]
#EOF



--- curl -v http://mac.local.host/ping

#--- Со следующим правилом проблема - применимо только для HTTP
#oc apply -f - <<EOF
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: allow-access-to-ingress
#  namespace: istio-system
#spec:
#  action: ALLOW
#  selector:
#    matchLabels:
#      app: ingress-api-gateway
#  rules:
#    - to:
#        - operation:
#            hosts:
#              - "*.apps-crc.testing"
#EOF

#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: deny-all
#  namespace: istio-system
#spec:
#  {}
#---
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: allow-inside-namespace
#  namespace: tutorial
#spec:
#  action: ALLOW
#  rules:
#    - to:
#        - operation:
#            hosts:
#            - "spring-boot-rest-client-tutorial.apps-crc.testing"
#    - from:
#        - source:
#            namespaces: ["tutorial"]
#---
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: allow-between-namespaces
#  namespace: tutorial2
#spec:
#  action: ALLOW
#  rules:
#    - to:
#        - operation:
#            hosts:
#              - "spring-boot-rest-server-svc.tutorial2.svc.cluster.local"
#    - from:
#        - source:
#            namespaces: ["tutorial"]
#---
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: allow-inside-namespace
#  namespace: tutorial2
#spec:
#  action: ALLOW
#  rules:
#    - to:
#        - operation:
#            hosts:
#              - "mac.local.host"
#    - from:
#        - source:
#            namespaces: ["tutorial2"]
