apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: istio-system
spec:
  {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-inside-namespace
  namespace: tutorial
spec:
  action: ALLOW
  rules:
    - to:
        - operation:
            hosts:
            - "spring-boot-rest-client-tutorial.apps-crc.testing"
    - from:
        - source:
            namespaces: ["tutorial"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-between-namespaces
  namespace: tutorial2
spec:
  action: ALLOW
  rules:
    - to:
        - operation:
            hosts:
              - "spring-boot-rest-server-svc.tutorial2.svc.cluster.local"
    - from:
        - source:
            namespaces: ["tutorial"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-inside-namespace
  namespace: tutorial2
spec:
  action: ALLOW
  rules:
    - to:
        - operation:
            hosts:
              - "mac.local.host"
    - from:
        - source:
            namespaces: ["tutorial2"]