--- Запрещаем все взаимодействия внутри SM

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: istio-system
spec:
  {}

--- Разрешаем любое взаимодействие внутри Namespace

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-inner-communications
  namespace: tutorial
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["tutorial", "istio-system"]

--- Разрешаем любое взаимодействие внутри Namespace

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-inner-communications
  namespace: tutorial2
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["tutorial2", "istio-system"]

---

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-access-to-ingress
  namespace: istio-system
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: ingress-api-gateway
  rules:
    ### TODO-выяснить применимо ли к TCP
    - {}

---


apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-access-to-egress
  namespace: istio-system
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: egress-api-gateway
  rules:
    ### TODO-выяснить применимо ли к TCP
    - {}