kind: ConfigMap
apiVersion: v1
metadata:
  name: spring-boot-rest-cfg
data:
  next.service.uri: http://spring-boot-rest-server-svc.tutorial2.svc.cluster.local:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-rest-client
    version: v1
  name: spring-boot-rest-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-rest-client
      version: v1
  template:
    metadata:
      labels:
        app: spring-boot-rest-client
        group: tutorial-rest-app
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"                 # service mesh sidecar
#        sidecar.istio.io/rewriteAppHTTPProbers: "true"  # settings for probe when mTLS enabled
    spec:
      containers:
        - env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: JAVA_OPTS
              value: -Dcom.sun.management.jmxremote
                -Dcom.sun.management.jmxremote.port=9998
                -Dcom.sun.management.jmxremote.rmi.port=9998
                -Dcom.sun.management.jmxremote.authenticate=false
                -Dcom.sun.management.jmxremote.ssl=false
                -Dcom.sun.management.jmxremote.local.only=false
            - name: NEXT_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-rest-cfg
                  key: next.service.uri
          name: spring-boot-rest-client
          image: image-registry.openshift-image-registry.svc:5000/tutorial/spring-boot-rest-client:apV2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9998
              name: tcp-jmx
              protocol: TCP
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          securityContext:
            privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-rest-client-svc
  labels:
    app: spring-boot-rest-client
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: spring-boot-rest-client
