kind: ConfigMap
apiVersion: v1
metadata:
  name: big-file-download-cfg
data:
  next.service.uri: http://ext-service.dso-api-gateway.svc.cluster.local:8083
#  next.service.uri: http://mac.local.host:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: big-file-download-server
    version: v1
  name: big-file-download-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: big-file-download-server
      version: v1
  template:
    metadata:
      labels:
        app: big-file-download-server
        group: tutorial-rest-app
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"                       # service mesh sidecar
        sidecar.istio.io/rewriteAppHTTPProbers: "true"        # settings for probe when mTLS enabled
#        traffic.sidecar.istio.io/excludeOutboundPorts: '8080'
        sidecar.maistra.io/proxyCPULimit: '500m'
        sidecar.maistra.io/proxyMemoryLimit: '500M'
    spec:
      containers:
        - env:
            - name: NEXT_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: big-file-download-cfg
                  key: next.service.uri
          name: big-file-download-server
          image: di-oscp-nxs-ci.corp.dev.vtb/usbp-docker-lib/apigw/big-file-download-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "1000Mi"
          securityContext:
            privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: big-file-download-server-svc
  labels:
    app: big-file-download-server
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: big-file-download-server
