kind: ConfigMap
apiVersion: v1
metadata:
  name: spring-boot-rest-cfg
data:
  next.service.uri: http://ext-service.tutorial2.svc.cluster.local
#  next.service.uri: http://mac.local.host
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-rest-server
    version: v1
  name: spring-boot-rest-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-rest-server
      version: v1
  template:
    metadata:
      labels:
        app: spring-boot-rest-server
        group: tutorial-rest-app
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"                 # service mesh sidecar
#        sidecar.istio.io/rewriteAppHTTPProbers: "true"  # settings for probe when mTLS enabled
    spec:
      containers:
        - env:
            - name: NEXT_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-rest-cfg
                  key: next.service.uri
          name: spring-boot-rest-server
          image: image-registry.openshift-image-registry.svc:5000/tutorial2/spring-boot-rest-server:apV2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          securityContext:
            privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-rest-server-svc
  labels:
    app: spring-boot-rest-server
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: spring-boot-rest-server
